### PR TITLE
Template refactorization + internal home page + model history

### PR DESCRIPTION
**Pull request by ddabble**
*Depends on #358, and should change base to `dev` after that PR has been merged.*

### Main highlights
* Refactored most edit forms to use same template (1ebbf97f62b43fd7aa342c58876c3124045cea5c)
  * Made [`contentbox/edit.html`](https://github.com/MAKENTNU/web/commit/bbd6fa9271a81f2915ba23a82a1d25b4dec3ad45#diff-9c3174720dd33061749dcdb43cbe5ed081f70dd40fd2ae08c906256908c030e4) extend the generic one (bbd6fa9271a81f2915ba23a82a1d25b4dec3ad45)
* Made `ContentBox` subdomain-agnostic (5c0e6a2b96777d93205b8d08cb45cc47f0b26aa1)
* Made the internal home page a content box (880a6cb9ef7d6633e051bc0de30d19ca916fe3b9) that allows editing the HTML source code (9156202b6ae9f6fd2312ff07f6f20af04d7d114d) and that only uses Norwegian (4ad67b746320bff1fa96ece77be22250f18af006)
* Added bleaching of content boxes (39b640a578a77c4f12f480cdb9a40cc3635425a7)
* Enabled content boxes requiring extra permissions to modify them, through the field `extra_change_permissions` (4a0348fdb457a105ad32e6e9aa61a6725c877e2e)
* Added [`django-simple-history`](https://pypi.org/project/django-simple-history/) for some models (fa62d9fda26c17950b073f7e95f239efde098165)
  * This adds history tracking to the `ContentBox`, `Question`, `Committee`, `Secret`, `MachineUsageRule`, `Event` and `Article` models
  * Site admins can view this history through the Django admin page for each model object, and have the option to revert the object to a specific historic version
* Improved layout of the CKEditor toolbar (68012913c03308871d3a2897591a46e9ae2ac182)

### Additional highlight
* Refactored [`ReservationRule.start_days`](https://github.com/MAKENTNU/web/commit/516cf75a0ea695a9fd65e34f12d5c4d4497a19bd#diff-7460e26a8f8c1ac0a038f4a7400923fc4bd0a3a54392e1c90a4bd6f6e1b00a9fR265) (516cf75a0ea695a9fd65e34f12d5c4d4497a19bd)
* Moved ReservationRule validation to form (1bfa14cd2b5c614af726dbbbdb735726eab5efc9)
* Renamed `Content.changed` -> [`last_modified`](https://github.com/MAKENTNU/web/commit/25afa8283a5e0702e8efb0392a2f1aeca1b6b3fd#diff-e980a9c9be3aa416c154e7f90f01ae8129dc6409072cd94510e22a8d577e3f96R54) (25afa8283a5e0702e8efb0392a2f1aeca1b6b3fd)
* Added some fields to the Django admin page for system accesses (dd68be1c04bb2714f651901397c1265793145aad)
* Added tests for all Django admin `GET` endpoints (5060e706c240c377b4d0675b6817d5e7581b68bb)

### CODE REVIEW

**Review by Maisergodt — CHANGES_REQUESTED** [review]
I have only have tested the content box and the history function (a neat feature to have), and have not looked at the code so you are aware of that. 

- [ ] History function for `Article` and `Event` seems to work as intended. Haven't tested it for `ContentBox` due to not being able to update current boxes as described in detail below (although I am sure it should work for `ContentBox` as intended too).

- [ ] Content box 
When editing existing content box on the main page, the English section is gone. Additionally when trying to save it, an error message is raised. The same behavior goes for the content box on the internal page as well. 
image

**Comment by ddabble** [comment]
@Maisergodt
> * When editing existing content boxes on the main page, the English section is gone.

Yes, that's on purpose (see 4ad67b746320bff1fa96ece77be22250f18af006), as it removes the hassle of translating all of the text and copying code from one language to the other 😊 Besides, all members are required to be able understand written Norwegian anyway 😅

> * Additionally when trying to save a content box, an error message is raised. The same behavior goes for the content box on the internal page as well.

Hm, that's weird, as I've written tests that explicitly test this case (see [internal/tests/test_views.py](https://github.com/MAKENTNU/web/commit/4ad67b746320bff1fa96ece77be22250f18af006#diff-d361ca73d0ece76d1eec6e73e60b9a696cf3f07026e785a0819f979099232676R78)), and I'm unable to reproduce the error you're getting (even when manually clearing the value of both languages in my local database, which I thought could be the cause) 😮🤔

**Comment by Maisergodt** [comment]
@ddabble 
> Hm, that's weird, as I've written tests that explicitly test this case for the internal home content box (see [internal/tests/test_views.py](https://github.com/MAKENTNU/web/commit/4ad67b746320bff1fa96ece77be22250f18af006#diff-d361ca73d0ece76d1eec6e73e60b9a696cf3f07026e785a0819f979099232676R78)), and I'm unable to reproduce the error you're getting (even when manually clearing the value of both languages in my local database, which I thought could be the cause) 🤔

The tests for internal content box are working, I spoke to quickly. It does indeed work for the content box on the internal page as intended, but the bugs on the main page still holds. 

> Has maybe something unusual happened to your local code or database, or should we try to reproduce the discrepancy on more machines? 

I can debug it thoroughly later today/this weekend and spot if anything is unusual on my end. It does not hurt if other members could test it as well 👀

**Comment by ddabble** [comment]
@Maisergodt I'm fairly positive that it's been fixed now, would you mind testing again? 😊

**Pull request merged**
