### PR TITLE
Fix for navbar user dropdown on mobile.

### PR DESCRIPTION
**Pull request by zootos**
Fixes two issues with the user dropdown on mobile.
- The dropdown is now initially closed
- `.dropdown()` was called on the dropdown icon, creating an extra div

Also fixes an issue, where Cmd/Ctrl clicking a link in the dropdown would change the dropdown text (the name), to the text of the selected link.

### CODE REVIEW

**Comment by ddabble** [comment]
Getting a `Dropdown: The method you called is not defined. ["nothing"]` error, from `$('#nav-user-dropdown').dropdown(action="nothing")` in `header.html:93`..?

**Comment by zootos** [comment]
@ddabble I have fixed that now. I did some testing with other actions than `select` and must have forgotten to switch back when staging.

**Comment by ddabble** [comment]
Hm, the items in the dropdown still get marked as selected, which looks a bit weird.. Also, think I found the proper way to pass the action argument, pushing now:

**Comment by ddabble** [comment]
Is this okay? :)

**Comment by zootos** [comment]
Yeah, I think so. The dropdown remains open, which seems weird at first. However, it might actually be better to leave it open than close it.

**Comment by ddabble** [comment]
Yeah, agree with that latter point, as it seems to be the norm on other websites 👍 Merging!

**Pull request merged**
